name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    uses: dxos/community-plugins/.github/workflows/release-plugin.yml@main
    with:
      bump: ${{ inputs.bump }}
    secrets: inherit
